service: auth-hook
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  stage: dev

functions:
  permissionCheck:
    handler: handler.permissionCheck
    events:
      - httpApi:
          path: /
          method: get
