on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
    paths:
      - 'backend/**'
  workflow_dispatch:

name: Build Docker image

jobs:
  build:
    name: Build Docker image
    uses: code4romania/.github/.github/workflows/build-push-image-ecr.yml@main
    with:
      image_name: onghub
      region: eu-west-1
      dockerfile: ./backend/Dockerfile
    secrets:
      role_to_assume: ${{ secrets.ROLE_TO_ASSUME }}